# Generated by Django 2.1.7 on 2019-06-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercados_de_prediccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinedcommunity',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Community'),
        ),
        migrations.AddField(
            model_name='joinedcommunity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Market'),
        ),
        migrations.AddField(
            model_name='asset',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Market'),
        ),
        migrations.AddField(
            model_name='asset',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Option'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
