# Generated by Django 2.1.7 on 2019-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0002_auto_20190519_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
