# Generated by Django 2.1.7 on 2019-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0002_auto_20190510_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_es',
            field=models.CharField(default='categoria en español por defecto', max_length=140, verbose_name='Title in Spanish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title in English'),
        ),
    ]
