# Generated by Django 2.1.7 on 2019-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0002_auto_20190618_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='is_yes',
            new_name='is_correct',
        ),
    ]
