# Generated by Django 2.1.7 on 2019-05-20 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0003_auto_20190519_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
