# Generated by Django 2.1.7 on 2019-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0003_auto_20190511_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.TextField(blank=True, null=True, verbose_name='Picture'),
        ),
    ]
