# Generated by Django 2.1.7 on 2019-06-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0003_auto_20190629_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='is_correct',
            new_name='is_yes',
        ),
    ]
