# Generated by Django 2.1.7 on 2019-05-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0004_market_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Market'),
            preserve_default=False,
        ),
    ]
