# Generated by Django 2.1.7 on 2019-05-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0004_group_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercados_de_prediccion.Group'),
        ),
    ]
