# Generated by Django 2.1.7 on 2019-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0005_market_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='judgement_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
