# Generated by Django 2.1.7 on 2019-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0006_market_is_binary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
