# Generated by Django 2.1.7 on 2019-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0007_auto_20190521_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
        migrations.RemoveField(
            model_name='market',
            name='category',
        ),
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ManyToManyField(to='mercados_de_prediccion.Category'),
        ),
    ]
