# Generated by Django 2.1.7 on 2019-05-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0007_auto_20190514_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedgroup',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
