# Generated by Django 2.1.7 on 2019-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0010_auto_20190528_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
