# Generated by Django 2.1.7 on 2019-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0012_price_is_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='option',
            name='binary_yes',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
