# Generated by Django 2.1.7 on 2019-06-09 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados_de_prediccion', '0014_price_is_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='buy_price',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
