# Generated by Django 2.1.7 on 2019-07-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verifyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifyrequest',
            old_name='biography',
            new_name='description',
        ),
    ]
